export const dashboardBusinessCss = `
.mb-text-navy{color:#1D1916}.mb-text-ink{color:#1D1916}.mb-text-subtle{color:#3B332D}.mb-text-body{color:#5F554C}.mb-text-muted{color:#6E6258}.mb-text-light{color:#8b8490}.mb-text-brown{color:#8F6B4C}.mb-text-accent{color:#A7815E}.mb-text-accent-strong{color:#8F6B4C}.mb-text-accent-dark{color:#8F6B4C}.mb-text-personal-accent{color:#A7815E}.mb-text-green{color:#197a39}.mb-text-green-strong{color:#087342}.mb-text-warn{color:#B89A7A}.mb-text-gray{color:#6E6258}.fill-mb-navy{fill:#1D1916}
.mb-border-line{border-color:#e8e1db}.mb-border-page{border-color:#eee7e0}.mb-border-soft{border-color:#e9e1db}.mb-border-subtle{border-color:#f0e9e4}.mb-border-hero{border-color:#e5ddd7}.mb-border-action{border-color:#e2cfc0}.mb-border-accent{border-color:#A7815E}.mb-border-green{border-color:#197a39}.mb-border-warn{border-color:#B89A7A}.mb-border-muted{border-color:#a8a8b4}.mb-border-user{border-color:#d8c5b7}.mb-border-draft{border-color:#d8b69e}.mb-border-upload{border-color:#e4d7ce}.mb-border-inset{border-color:#e7ddd6}.mb-border-footer{border-color:#ece5df}.mb-border-header{border-color:#ede4dd}.mb-border-individual{border-color:#e9dfd6}.mb-border-individual-soft{border-color:#eadcd2}.mb-border-individual-line{border-color:#eee4dc}.hover\\:mb-border-hover:hover{border-color:#B89A7A}
.mb-bg-accent{background-color:#A7815E}.mb-bg-green{background-color:#197a39}.mb-bg-accent-soft{background-color:#fbf4ef}.mb-bg-green-soft{background-color:#edf8ef}.mb-bg-success-soft{background-color:#edf6ef}.mb-bg-tag{background-color:#fff4e8}.mb-bg-paper{background-color:#fffdfb}.mb-bg-line{background-color:#d7c9bf}.mb-bg-nav-active{background-color:#f7eee7}.mb-bg-cream{background-color:#F6F4F1}.mb-bg-warm{background-color:#fff7ea}.mb-bg-brown-soft{background-color:#fff8f1}.mb-bg-divider{background-color:#eaded4}.mb-bg-personal-active{background-color:#f6e9e2}.mb-bg-legacy-active{background-color:#f4ebe5}.mb-bg-red{background-color:#8F6B4C}.mb-bg-notice{background-color:#A7815E}.mb-bg-individual-line{background-color:#e9dfd6}.hover\\:mb-bg-hover:hover{background-color:#fffaf5}.hover\\:mb-bg-nav:hover{background-color:#fbf5ef}.hover\\:mb-bg-warm:hover{background-color:#fff7ea}.hover\\:mb-bg-legacy:hover{background-color:#faf4ed}.hover\\:mb-bg-personal:hover{background-color:#fbf3ee}.hover\\:mb-text-accent:hover{color:#A7815E}.hover\\:mb-text-accent-dark:hover{color:#8F6B4C}.hover\\:mb-text-personal-accent:hover{color:#A7815E}.hover\\:mb-text-legacy-accent:hover{color:#8F6B4C}.after\\:mb-bg-personal-accent::after{background-color:#A7815E}
.mb-shadow-card{box-shadow:0 10px 20px rgb(29 25 22 / .025)}.mb-shadow-panel{box-shadow:0 10px 20px rgb(29 25 22 / .018)}.mb-shadow-hero{box-shadow:0 12px 28px rgb(29 25 22 / .025)}.mb-shadow-send{box-shadow:0 10px 24px rgb(167 129 94 / .22)}.mb-shadow-shell{box-shadow:0 18px 45px rgb(29 25 22 / .04)}.mb-shadow-sidebar{box-shadow:0 18px 55px rgb(29 25 22 / .06)}.mb-shadow-legacy-top{box-shadow:0 14px 38px rgb(29 25 22 / .055)}.mb-shadow-inset{box-shadow:inset 0 0 0 1px rgb(232 210 195 / .9)}
.mb-hero-fade{background:linear-gradient(90deg,rgb(255 255 255 / .03),rgb(255 255 255 / .42) 36%,rgb(255 255 255 / .97) 68%,#fff 100%)}.mb-contribution-hero-fade{background:linear-gradient(90deg,rgb(255 255 255 / .02),rgb(255 255 255 / .4) 45%,rgb(255 255 255 / .96) 70%,#fff 100%)}.mb-legacy-backdrop{background:radial-gradient(circle at 12% 3%,rgb(167 129 94 / .08),transparent 24rem),radial-gradient(circle at 84% 8%,rgb(29 25 22 / .04),transparent 24rem)}
.business-stats-grid,.business-performance-grid{grid-template-columns:repeat(6,minmax(0,1fr))}
.business-kpi-grid{grid-template-columns:repeat(6,minmax(0,1fr))}
.business-contribution-layout{grid-template-columns:300px minmax(0,1fr)}
.business-list-layout{grid-template-columns:300px minmax(0,1fr)}
.business-profile-layout{grid-template-columns:300px minmax(0,1fr)}
.contribution-row-grid{grid-template-columns:130px minmax(0,1fr) 190px}
.business-trust-grid{grid-template-columns:repeat(4,minmax(0,1fr))}
.business-submit-grid{grid-template-columns:minmax(0,1fr) 280px}
.business-sticky-actions{background:#1D1916}
.business-header-nav a{margin-inline:22px}
@media(max-width:1279px){.business-stats-grid,.business-performance-grid,.business-kpi-grid{grid-template-columns:repeat(3,minmax(0,1fr))}.business-trust-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}
@media(max-width:1023px){.business-stats-grid,.business-performance-grid,.business-kpi-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.business-contribution-layout,.business-submit-grid,.business-list-layout,.business-profile-layout,.contribution-row-grid{grid-template-columns:1fr}}
@media(max-width:640px){.business-stats-grid,.business-performance-grid,.business-kpi-grid,.business-trust-grid{grid-template-columns:1fr}}
`;
