// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/assets" | "/assets/[slug]" | "/auth/[[...slug]]" | "/blog" | "/blog/[slug]" | "/contact" | "/contributions" | "/contributions/[slug]" | "/dashboard" | "/dashboard/[role]/[[...slug]]" | "/disclaimer" | "/faq" | "/media" | "/media/[slug]" | "/news" | "/news/[slug]" | "/privacy" | "/request-study" | "/services" | "/services/[slug]" | "/submit-asset" | "/terms"
type AppRouteHandlerRoutes = "/api/articles" | "/api/assets" | "/api/assets/[slug]" | "/api/auth/login" | "/api/auth/logout" | "/api/auth/onboarding" | "/api/auth/register" | "/api/auth/verify" | "/api/contact" | "/api/content-comments" | "/api/content-save" | "/api/contributions" | "/api/contributions/[slug]" | "/api/dashboard/account-settings" | "/api/dashboard/accounts" | "/api/dashboard/admin-management" | "/api/dashboard/admin-messages" | "/api/dashboard/admin-notifications" | "/api/dashboard/admin-support" | "/api/dashboard/document" | "/api/dashboard/financial" | "/api/dashboard/financial/pay" | "/api/dashboard/financial/subscription" | "/api/dashboard/interest" | "/api/dashboard/messages" | "/api/dashboard/notifications" | "/api/dashboard/request" | "/api/dashboard/review" | "/api/dashboard/support" | "/api/dashboard/verification" | "/api/newsletter" | "/api/request-study" | "/api/services" | "/api/submit-asset" | "/api/system/status"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/api/articles": {}
  "/api/assets": {}
  "/api/assets/[slug]": { "slug": string; }
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/onboarding": {}
  "/api/auth/register": {}
  "/api/auth/verify": {}
  "/api/contact": {}
  "/api/content-comments": {}
  "/api/content-save": {}
  "/api/contributions": {}
  "/api/contributions/[slug]": { "slug": string; }
  "/api/dashboard/account-settings": {}
  "/api/dashboard/accounts": {}
  "/api/dashboard/admin-management": {}
  "/api/dashboard/admin-messages": {}
  "/api/dashboard/admin-notifications": {}
  "/api/dashboard/admin-support": {}
  "/api/dashboard/document": {}
  "/api/dashboard/financial": {}
  "/api/dashboard/financial/pay": {}
  "/api/dashboard/financial/subscription": {}
  "/api/dashboard/interest": {}
  "/api/dashboard/messages": {}
  "/api/dashboard/notifications": {}
  "/api/dashboard/request": {}
  "/api/dashboard/review": {}
  "/api/dashboard/support": {}
  "/api/dashboard/verification": {}
  "/api/newsletter": {}
  "/api/request-study": {}
  "/api/services": {}
  "/api/submit-asset": {}
  "/api/system/status": {}
  "/assets": {}
  "/assets/[slug]": { "slug": string; }
  "/auth/[[...slug]]": { "slug"?: string[]; }
  "/blog": {}
  "/blog/[slug]": { "slug": string; }
  "/contact": {}
  "/contributions": {}
  "/contributions/[slug]": { "slug": string; }
  "/dashboard": {}
  "/dashboard/[role]/[[...slug]]": { "role": string; "slug"?: string[]; }
  "/disclaimer": {}
  "/faq": {}
  "/media": {}
  "/media/[slug]": { "slug": string; }
  "/news": {}
  "/news/[slug]": { "slug": string; }
  "/privacy": {}
  "/request-study": {}
  "/services": {}
  "/services/[slug]": { "slug": string; }
  "/submit-asset": {}
  "/terms": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
